# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvirX_IFNlSemy62kZSRuXRiOej65mIE
"""

import joblib
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv('iris.csv')

df.head()

df.species.unique()

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False)
type_species = ohe.fit_transform(df[['species']])

type_species

type_species = pd.DataFrame(type_species, columns = ['setosa', 'versicolor', 'virginica'])

df.columns

X = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]
y = type_species['setosa']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

y_train.value_counts()

logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
logistic_model.score(X_test, y_test)

y_train_pred = logistic_model.predict(X_train)
y_test_pred = logistic_model.predict(X_test)

print(classification_report(y_train, y_train_pred))

print(classification_report(y_test, y_test_pred))

joblib.dump(logistic_model, 'model.joblib')